// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZDpSoCbi_P5qGiSJE_-nyh9Ametj2VCM',
    appId: '1:918712125734:android:2262e14a99a4f8e40799e7',
    messagingSenderId: '918712125734',
    projectId: 'selldyyab',
    storageBucket: 'selldyyab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQAaFWTMdTJI8gehA3zqM0F18i3iaSxE0',
    appId: '1:918712125734:ios:ed7dceb358ca001e0799e7',
    messagingSenderId: '918712125734',
    projectId: 'selldyyab',
    storageBucket: 'selldyyab.appspot.com',
    iosClientId: '918712125734-hhuag12fvrf6us6qfk1t4d4jh7jh6qq2.apps.googleusercontent.com',
    iosBundleId: 'com.selldy.yab',
  );
}
